# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Athan' do

pod 'BAPrayerTimes', '~> 1.4'
pod 'ASIHTTPRequest'
pod 'SDWebImage', '~>3.7'
pod 'mopub-ios-sdk'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'
pod 'FMDB'

end

